[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stabilvol"
version = "0.1.0"
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["."]
include = ["stabilvol*"]